version: "3.0"

services:
  db-postgres-titanic:
    container_name: postgres_titanic_container
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: titanicapi
      POSTGRES_USER: postgres
        POSTGRES_PASSWORD: System20
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres:
    driver: local
